version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./artifacts/schema:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=app
    - MYSQL_USER=user
    - MYSQL_PASSWORD=app